### ISSUE TITLE
Holidays not archiving correctly

### ISSUE THREAD

**Issue by jmartin-nsc** [infsy/Kentel#6] opened 2017-05-12 19:07 UTC
Auto-archiving of entries in the project "vacances" does not work. Past entries do not get their "DeletedAt" field updated as it should.

Also, we got a bug after a reboot that seems related: all "vacances" entries that have their "DeletedAt" field set to NULL have been updated to the time of the reboot, which of course have hidden all this information from the interface. We had to update the table to remove this false information.

Thanks!

**Comment by infsy** [comment] 2017-05-12 19:13
Do you had any other entries with this kind of bug after reboot ? This is weird that a reboot could change anything to the table content... For the first point i take in charge quickly.

Thanks for the report in english by the way ;-)

**Comment by jmartin-nsc** [comment] 2017-05-12 19:18
It seems the only project affected was "vacances" (mandat_id 66)

**Comment by infsy** [comment] 2017-05-19 17:12
I can't reproduce the problem. Could you please send me the content of your crontab on your server relative to kentel. 
And the result of a git status command.
Thanks

**Comment by infsy** [comment] 2017-08-26 16:15
Last commit (2a9345a3e9e3fa11d83b75514e68a24ec834ad5a) include the utilization of deletedat field. 
Without any additional info i close this ticket. Feel you free to open another one if any bug persist with more information.

**Closed by infsy** 2017-08-26 16:15 UTC
Labels: bug
